FORMAT: 1A

# OASIS.PLATFORM API文档

绿洲平台API全文档

## 获取所有游戏世界 [/games]

### 获取所有游戏世界 [GET]

+ Parameters
    + bc (string) - 区块链网络，"eth" or "eos" or "trx" or "hyperchain"

+ Response 200 (application/json)

    + Attributes (array[Game])



## 指定游戏世界 [/game/{id}] 

`id`为游戏世界在中心化数据库内的id

### 获取游戏世界详情 [GET]

+ Parameters
    + id (number) - 游戏世界id
    + bc (number) - 区块链网络, "eth" or "eos" or "trx" or "hyperchain"

+ Response 200 (application/json)

    + Attribute (Game)

### 添加游戏世界 [POST]

该API是在平台的中心化后端添加记录，项目方须首先自行在OASIS.MAIN合约中添加记录。

+ Request (application/json)

    + Attributes

        + bc (string) - 区块链网络, "eth" or "eos" or "trx" or "hyperchain"
        + name (string) - 自定义的游戏名
        + worldName (string) - 在合约中的世界名
        + extMetaUrl (string) - 用于提供扩展元数据的api地址

+ Response 200 (application/json)

    + Attributes

        + code (number) - 操作码
        + msg (string) - 响应信息

### 删除游戏世界 [DELETE]

+ Parameters
    + id (number) - 游戏世界id
    + bc (number) - 区块链网络, "eth" or "eos" or "trx" or "hyperchain"

+ Response 200 (application/json)

    + Attribute (Game)

## 道具资产 [/items/{gid}]

### 获取所有道具资产 [GET]

获取某用户在某游戏的所有道具资产

+ Parameters

    + gid (number) - 游戏世界id
    + owner (string) - 用户地址或账户名
    + bc (string) - 区块链网络，"eth" or "eos" or "trx" or "hyperchain"
    + hasProps (boolean, optional) - 是否返回`properties`字段（有一定字节开销）

+ Response 200 (application/json)

    + Attributes (array[NFT])


## 单个道具资产 [/item/{gid}/{uuid}] 

### 获取道具资产详情 [GET]

获取某给定道具的扩展信息

+ Parameters

    + uuid (number) - NFT Global id
    + gid (number) - 游戏世界id
    + bc (string) - 区块链网络,"eth" or "eos" or "trx" or "hyperchain"
    + hasProps (boolean, optional) - 是否返回`properties`字段（有一定字节开销）

+ Response 200 (application/json)

    + Attributes(NFT)


## Data Structures

### NFT
+ uuid: 1234 (number, required)
+ uri: oasis://0xabcdef123456/game/ARMOR/cat (string, required)
+ symbol: SWORD (string, required)
+ contract: 0xabcdef123456 (string, required)
+ game: rogeman (string, required)
+ type: ARMOR (string, required)
+ category: cat (string, required)
+ img: https://google.com/image/xxx.jpg (string, required)
+ name: 圣诞老人猫 (string, required)
+ desc: 这是一只猫
+ properties (object)

### Game
+ id: 12345 (number, required)
+ name: 谜恋猫 (required)
+ logo: ""
+ platform: eth
+ worldContract: 0xabcdef1234 (required)
+ worldName: cryptokitties (required)
