FORMAT: 1A

# OASIS.PLATFORM API文档

绿洲平台API全文档

## 通用的返回结构体

- code (number)
- msg (string)
- data (object) - 以下API的返回值均指该字段


## 获取所有游戏世界 [/games?bc={bc}]

### 获取所有游戏世界 [GET]

+ Parameters
    + bc (string, optional) - 区块链网络，"eth" or "eos" or "trx" or "hyperchain"。空值代表返回所有。

+ Response 200 (application/json)

    + Attributes (array[Game])



## 指定游戏世界 [/game/{id}] 

`id`为游戏世界在中心化数据库内的id

### 获取游戏世界详情 [GET]

+ Parameters
    + id (string) - 游戏世界id

+ Response 200 (application/json)

    + Attribute (Game)

### 添加游戏世界 [POST]

该API是在平台的中心化后端添加记录，项目方须首先自行在OASIS.MAIN合约中添加记录。

+ Request (application/json)

    + Attributes

        + bc (string) - 区块链网络, "eth" or "eos" or "trx" or "hyperchain"
        + name (string) - 自定义的游戏名
        + worldName (string) - 在合约中的世界名

+ Response 200 (application/json)

    + Attributes

        + code (number) - 操作码
        + msg (string) - 响应信息

### 删除游戏世界 [DELETE]

+ Parameters
    + id (string) - 游戏世界id

+ Response 200 (application/json)

    + Attribute (Game)

## 道具资产 [/items/{gid}?owner={owner}[&simple={simple}&hasProps={hasProps}]]

### 获取可转移的道具资产 [GET]

获取某用户在某游戏下的所有可转移的道具资产。

+ Parameters

    + gid (string) - 游戏世界id
    + owner (string) - 用户地址或账户名
    + simple (boolean, optional) - 是否只返回简单的数据项，默认为false
    + hasProps (boolean, optional) - 是否返回`properties`字段（有一定字节开销），默认为false

+ Response 200 (application/json)

    + Attributes (array[SimpleNFT]) 
    + Attributes (array[NFT]) 

## 道具详细数据 [/item/{gid}/{uuid}[?hasProps={hasProps}]]

该API仅使用NFT的UUID来获取详情，后端需要遍历关联的资产合约查询数据，速度较慢。

### 获取道具资产详情 [GET]

获取某给定道具的扩展信息

+ Parameters

    + uuid (string) - NFT Global id
    + gid (string) - 游戏世界id
    + hasProps (boolean, optional) - 是否返回`properties`字段（有一定字节开销）

+ Response 200 (application/json)

    + Attributes(NFT)


## 道具扩展元数据 [/preview/{gid}/{uuid}?uri={uri}&symbol={symbol}]

该API直接提供NFT的三个关键元数据，在后端可直接调用项目方的metaUrl进行扩展元数据解析，速度较快。

### 获取道具预览数据 [GET]

+ Parameters 

    + uuid (string) - NFT Global id
    + gid (string) - 游戏世界id
    + uri (string) - NFT URI
    + symbol (string) - NFT Symbol

+ Response 200 (application/json)

    + Attributes(NFT)

## 映射关系 [/mapping/{symbol}?from={fromGameID}&to={toGameID}]

获取指定道具在指定游戏中的映射

### 获取所有映射 [GET]

+ Parameters

    + gid (string) - 游戏世界id
    + symbol (string) - 游戏道具的symbol

+ Response 200 (application/json)

    + Attributes (array[Mapping])

## Data Structures

### Common
+ code: 0 (number,required)
+ msg: 'success' (string)
+ data (object)

### SimpleNFT
+ uuid: 1234 (string, required)
+ uri: oasis://0xabcdef123456/game/ARMOR/cat (string, required)
+ symbol: SWORD (string, required)
+ name: 圣诞老人猫 (string, required)

### NFT (SimpleNFT)
+ contract: 0xabcdef123456 (string, required)
+ game: rogeman (string, required)
+ type: ARMOR (string, required)
+ category: cat (string, required)
+ img: https://google.com/image/xxx.jpg (string, required)
+ desc: 这是一只猫
+ properties (object)

### Game
+ id: 12345 (string, required)
+ name: 谜恋猫 (required)
+ logo: ""
+ platform: eth
+ worldContract: 0xabcdef1234 (required)
+ worldName: cryptokitties (required)

### Mapping
+ newSymbol 转移后的symbol (string, required)
+ logo (string)
